
package com.example.soapclient;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "AIP270AIPort", targetNamespace = "http://www.AIP270AI.REQMEM.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AIP270AIPort {


    /**
     * 
     * @param requestMessage
     * @return
     *     returns com.example.soapclient.ProgramInterface2.ResponseMessage
     */
    @WebMethod(operationName = "AIP270AIOperation")
    @WebResult(name = "responseMessage", targetNamespace = "http://www.CAIP234LO.com/schemas/CAIP234LOInterface")
    @RequestWrapper(localName = "AIP270AIOperation", targetNamespace = "http://www.CAIP234LI.com/schemas/CAIP234LIInterface", className = "com.example.soapclient.ProgramInterface")
    @ResponseWrapper(localName = "AIP270AIOperationResponse", targetNamespace = "http://www.CAIP234LO.com/schemas/CAIP234LOInterface", className = "com.example.soapclient.ProgramInterface2")
    public com.example.soapclient.ProgramInterface2 .ResponseMessage aip270AIOperation(
        @WebParam(name = "requestMessage", targetNamespace = "http://www.CAIP234LI.com/schemas/CAIP234LIInterface")
        com.example.soapclient.ProgramInterface.RequestMessage requestMessage);

}
