
package com.example.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AIP270AIService", targetNamespace = "http://www.AIP270AI.REQMEM.com", wsdlLocation = "file:/C:/clm/AIP270AI.wsdl")
public class AIP270AIService
    extends Service
{

    private final static URL AIP270AISERVICE_WSDL_LOCATION;
    private final static WebServiceException AIP270AISERVICE_EXCEPTION;
    private final static QName AIP270AISERVICE_QNAME = new QName("http://www.AIP270AI.REQMEM.com", "AIP270AIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/clm/AIP270AI.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AIP270AISERVICE_WSDL_LOCATION = url;
        AIP270AISERVICE_EXCEPTION = e;
    }

    public AIP270AIService() {
        super(__getWsdlLocation(), AIP270AISERVICE_QNAME);
    }

    public AIP270AIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AIP270AISERVICE_QNAME, features);
    }

    public AIP270AIService(URL wsdlLocation) {
        super(wsdlLocation, AIP270AISERVICE_QNAME);
    }

    public AIP270AIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AIP270AISERVICE_QNAME, features);
    }

    public AIP270AIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AIP270AIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AIP270AIPort
     */
    @WebEndpoint(name = "AIP270AIPort")
    public AIP270AIPort getAIP270AIPort() {
        return super.getPort(new QName("http://www.AIP270AI.REQMEM.com", "AIP270AIPort"), AIP270AIPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AIP270AIPort
     */
    @WebEndpoint(name = "AIP270AIPort")
    public AIP270AIPort getAIP270AIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.AIP270AI.REQMEM.com", "AIP270AIPort"), AIP270AIPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AIP270AISERVICE_EXCEPTION!= null) {
            throw AIP270AISERVICE_EXCEPTION;
        }
        return AIP270AISERVICE_WSDL_LOCATION;
    }

}
